PRODUCT_VERSION_MAJOR = 8
PRODUCT_VERSION_MINOR = 0

ifeq ($(AFTERLIFE_VERSION_APPEND_TIME_OF_DAY),true)
    AFTERLIFE_BUILD_DATE := $(shell date -u +%Y%m%d_%H%M%S)
else
    AFTERLIFE_BUILD_DATE := $(shell date -u +%Y%m%d)
endif

# Set AFTERLIFE_BUILDTYPE from the env RELEASE_TYPE, for jenkins compat

ifndef AFTERLIFE_BUILDTYPE
    ifdef RELEASE_TYPE
        # Starting with "AFTERLIFE_" is optional
        RELEASE_TYPE := $(shell echo $(RELEASE_TYPE) | sed -e 's|^AFTERLIFE_||g')
        AFTERLIFE_BUILDTYPE := $(RELEASE_TYPE)
    endif
endif

# Filter out random types, so it'll reset to UNOFFICIAL
ifeq ($(filter RELEASE NIGHTLY SNAPSHOT EXPERIMENTAL,$(AFTERLIFE_BUILDTYPE)),)
    AFTERLIFE_BUILDTYPE := UNOFFICIAL
    AFTERLIFE_EXTRAVERSION :=
endif

ifeq ($(AFTERLIFE_BUILDTYPE), UNOFFICIAL)
    ifneq ($(TARGET_UNOFFICIAL_BUILD_ID),)
        AFTERLIFE_EXTRAVERSION := -$(TARGET_UNOFFICIAL_BUILD_ID)
    endif
endif

AFTERLIFE_VERSION_SUFFIX := $(AFTERLIFE_BUILD_DATE)-$(AFTERLIFE_BUILDTYPE)$(AFTERLIFE_EXTRAVERSION)-$(AFTERLIFE_BUILD)

# Internal version
AFTERLIFE_VERSION := $(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(AFTERLIFE_VERSION_SUFFIX)

# Display version
AFTERLIFE_DISPLAY_VERSION := $(PRODUCT_VERSION_MAJOR)-$(AFTERLIFE_VERSION_SUFFIX)

# AfterlifeOS version properties
PRODUCT_SYSTEM_PROPERTIES += \
    ro.afterlife.version=$(AFTERLIFE_VERSION) \
    ro.afterlife.display.version=$(AFTERLIFE_DISPLAY_VERSION) \
    ro.afterlife.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.afterlife.releasetype=$(AFTERLIFE_BUILDTYPE)
